name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: arboreal-cosmos-440011-r8        # ✅ Ganti sesuai project kamu
  REGION: asia-southeast2
  REPOSITORY_AKM: ci-artifact-registry
  IMAGE_NAME: akmal-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_AKM/$IMAGE_NAME:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_AKM/$IMAGE_NAME:latest
