name: Terraform Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    env:
      PROJECT_ID: var.project_id
      REGION: var.region
      REPOSITORY_AKM: var.repository_id  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Terraform Init
      run: terraform init

    - name: Try Import Artifact Registry (ignore errors if already imported)
      run: |
        terraform import google_artifact_registry_repository.registry \
          projects/${PROJECT_ID}/locations/${REGION}/repositories/${REPOSITORY_AKM} || true

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
