name: Terraform with Existing Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: arboreal-cosmos-440011-r8        # Ganti dengan project ID kamu
      REGION: asia-southeast2                      # Lokasi registry
      REPOSITORY_ID: ci-artifact-registry          # ID dari Artifact Registry yang SUDAH ADA

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Terraform Init
      run: terraform init

    - name: Import Existing Artifact Registry
      run: |
        echo "Importing registry if not already in state..."
        terraform state list | grep google_artifact_registry_repository.registry \
          || terraform import google_artifact_registry_repository.registry \
              projects/${PROJECT_ID}/locations/${REGION}/repositories/${REPOSITORY_ID}

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
